services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672"
  producer:
    build: ./producer-worker
  consumer1:
    build: ./consumer-worker
  consumer2:
    build: ./consumer-worker
