services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672"
      - "15672:15672"
  producer:
    build: ./producer
    environment:
      - "Topic=kernel"
  producer-printer:
    build: ./producer
    environment:
      - "Topic=printer"
  consumer:
    build: ./consumer
    environment:
      - "Topic=kernel.*"
  consumer-error:
    build: ./consumer
    environment:
      - "Topic=*.error"
